from PyQt4.QtCore import *
from PyQt4.QtGui import *

class ui():
  def __init__(self):
    self.main_frame = QDialog()
    self.main_frame.resize(1200,800)
       
  def change_message_text(self, text, critical=False):
    if critical:
      style = 'color: red;'
    else:
      style = 'color: black;'
    self.message_text.setStyleSheet(style)
    self.message_text.setText(text)
    
  def draw_ui(self, canvas):
    self.canvas = canvas 
    
    self.canvas.setParent(self.main_frame)
    self.canvas.setFocusPolicy(Qt.ClickFocus)
    self.canvas.setFocus()
    policy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.canvas.setSizePolicy(policy)
    
    button_style	 = "background-color: transparent; border: 1px solid black;" 
    alert_button_style	 = "background-color: red; border: 1px solid black;"  
    self.button_inspect = QToolButton()
    self.button_inspect.setStyleSheet(button_style)  
    self.button_inspect.setText("inspect")
    self.button_resize = QToolButton()
    self.button_resize.setStyleSheet(button_style)  
    self.button_resize.setText("resize")  
    self.button_mask_re = QToolButton()
    self.button_mask_re.setStyleSheet(button_style)  
    self.button_mask_re.setText("mask (rectangle)")  
    self.button_mask_ci = QToolButton()
    self.button_mask_ci.setStyleSheet(button_style)  
    self.button_mask_ci.setText("mask (circle)")  
    self.button_mask_param1 = QLineEdit()
    self.button_mask_param1.setStyleSheet(button_style)  
    self.button_mask_param1.setText("0")  
    self.button_mask_param1.setMaximumWidth(50)
    self.button_mask_param2 = QLineEdit()
    self.button_mask_param2.setStyleSheet(button_style)  
    self.button_mask_param2.setText("0")  
    self.button_mask_param2.setMaximumWidth(50) 
    self.button_mask_param3 = QLineEdit()
    self.button_mask_param3.setStyleSheet(button_style)  
    self.button_mask_param3.setText("0")  
    self.button_mask_param3.setMaximumWidth(50)    
    self.button_mask_param4 = QLineEdit()
    self.button_mask_param4.setStyleSheet(button_style)  
    self.button_mask_param4.setText("0")  
    self.button_mask_param4.setMaximumWidth(50)    
    self.button_mask_value = QLineEdit()
    self.button_mask_value.setStyleSheet(button_style)  
    self.button_mask_value.setText("0")  
    self.button_mask_value.setMaximumWidth(50)  
    self.button_mask_apply = QToolButton()
    self.button_mask_apply.setStyleSheet(button_style)  
    self.button_mask_apply.setText("apply mask")  
    self.button_fft = QToolButton()
    self.button_fft.setStyleSheet(button_style)  
    self.button_fft.setText("fft/ifft")  
    self.button_fftshift = QToolButton()
    self.button_fftshift.setStyleSheet(button_style)  
    self.button_fftshift.setText("fftshift/ifftshift")       
    self.button_nscaling = QToolButton()
    self.button_nscaling.setStyleSheet(button_style)  
    self.button_nscaling.setText("scaling+")      
    self.button_pscaling = QToolButton()
    self.button_pscaling.setStyleSheet(button_style)  
    self.button_pscaling.setText("scaling-")    
    self.button_pview = QToolButton()
    self.button_pview.setStyleSheet(button_style)  
    self.button_pview.setText("view-")   
    self.button_nview = QToolButton()
    self.button_nview.setStyleSheet(button_style)  
    self.button_nview.setText("view+")  
    self.button_resetview = QToolButton()
    self.button_resetview.setStyleSheet(button_style)  
    self.button_resetview.setText("reset view") 
    self.button_resetdata = QToolButton()
    self.button_resetdata.setStyleSheet(alert_button_style)  
    self.button_resetdata.setText("RESET")  
    
    toolbar_style = "spacing: 5px"
    self.message_text = QLabel()
    self.message_text.setAlignment(Qt.AlignRight)
    self.toolbar_actions = QToolBar(self.main_frame)
    self.toolbar_actions.setStyleSheet(toolbar_style )
    self.toolbar_mode = QToolBar(self.main_frame)
    self.toolbar_mode.setStyleSheet(toolbar_style )    
    self.toolbar_mode2 = QToolBar(self.main_frame)
    self.toolbar_mode2.setStyleSheet(toolbar_style )
    self.toolbar_controls = QToolBar(self.main_frame)
    self.toolbar_controls.setStyleSheet(toolbar_style )
    
    self.toolbar_mode.addWidget(self.button_inspect)
    self.toolbar_mode.addWidget(self.button_resize)
    self.toolbar_mode2.addWidget(self.button_mask_re)
    self.toolbar_mode2.addWidget(self.button_mask_ci)
    self.toolbar_mode2.addWidget(self.button_mask_param1)   
    self.toolbar_mode2.addWidget(self.button_mask_param2)  
    self.toolbar_mode2.addWidget(self.button_mask_param3)   
    self.toolbar_mode2.addWidget(self.button_mask_param4) 
    self.toolbar_mode2.addWidget(self.button_mask_value)
    self.toolbar_mode2.addWidget(self.button_mask_apply)    
    self.toolbar_actions.addWidget(self.button_fft)
    self.toolbar_actions.addWidget(self.button_fftshift) 
    self.toolbar_controls.addWidget(self.button_nscaling)  
    self.toolbar_controls.addWidget(self.button_pscaling) 
    self.toolbar_controls.addWidget(self.button_nview) 
    self.toolbar_controls.addWidget(self.button_pview)  
    self.toolbar_controls.addWidget(self.button_resetview)
    self.toolbar_controls.addWidget(self.button_resetdata)  
    
    self.layout = QGridLayout()
    self.layout.addWidget(self.message_text, 1, 1, 1, 2)
    self.layout.addWidget(self.canvas, 2, 1, 1, 1)
    self.layout.addWidget(self.toolbar_mode, 3, 1, 1, 2)
    self.layout.addWidget(self.toolbar_mode2, 4, 1, 1, 2)
    self.layout.addWidget(self.toolbar_actions, 5, 1, 1, 2)
    self.layout.addWidget(self.toolbar_controls, 6, 1, 1, 2) 
    self.main_frame.setLayout(self.layout)  